### ISSUE TITLE
Have few files?

### ISSUE THREAD

**Issue by kirito-0** [Shakleen/Vocab#2]
Have few files?
The project file cannot be opened, where is key.dart?

**Comment by Shakleen** [comment]
Hey there! It's been a while since I built this. If my memory serves me right, that file contained the API keys to use the Oxford Dictionary API. You can get your own keys from Oxford Dictionary for free. Just create an account there and get the API keys. Then create key.dart and place the keys there.

**Comment by kirito-0** [comment]
What is the format of key.dart? Is it directly a string of API keys?
